services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile

    image: eraniket/auth-service-dotnet:latest
    container_name: auth-service

    ports:
      - "5001:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=practicedb2;User Id=sa;Password=Aniket@12345;Encrypt=False;TrustServerCertificate=True;"
      Redis__ConnectionString: "redis:6379"

    depends_on:
      - redis

    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis

    ports:
      - "6379:6379"

    restart: unless-stopped